version: '3'
services:
  node:
    build:
      context: .
    tty: true
    # environment:
    #   - NODE_ENV=development
      # - PORT=3002
    # volumes:
    # - ./:/usr/src/app
    # command: sh -c "cd react-todo-js && npm install && npm start"
    # ports:
    # - "3000:3000"